name: spajam-product
options:
  bundleIdPrefix: com.litech
  developmentLanguage: ja
  preGenCommand: |
    mint bootstrap 
    chmod +x ./scripts/carthage.sh
    ./scripts/carthage.sh bootstrap --platform iOS --cache-builds
targets:
    spajam-product:
      type: application
      platform: iOS
      sources:
        - spajam-product
      
          
      settings:
        base:
          DEVELOPMENT_TEAM: 2X6AD4W323
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          MARKETING_VERSION: 1.0.0
          CURRENT_PROJECT_VERSION: 1
          FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: spajam-product/Info.plist
          OTHER_LDFLAGS:
            - $(inherited)
            - $(OTHER_LDFLAGS)
            - -ObjC
      preBuildScripts:
      dependencies:
        - carthage: RealmSwift
        - carthage: Realm
        - carthage: Action
        - carthage: RxSwift
        - carthage: RxCocoa
        - carthage: RxRelay
        - carthage: SVProgressHUD
        - carthage: RxAlamofire
        - carthage: Alamofire
        - target: Widgets
    Widgets:
      type: app-extension
      platform: iOS
      sources: Widgets
      settings:
        base: 
          INFOPLIST_FILE: ./Widgets/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: com.litech.spajam-product.widgets