name: Build Check

on: [push] 

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: '12.0'
    - name: Build
      run: xcodebuild -sdk iphonesimulator -scheme spajam-project -configuration Debug build 
