name: Build Check

on: [push] 

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: '12.0'
    - name: Install XcodeGen
      run: brew install xcodegen
    - name: Install Mint
      run: brew install mint
    - name: Cache Mint packages
      uses: actions/cache@v2
      with:
        path: mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - name: Generate Xcode project with XcodeGen
      run: xcodegen
    - name: Build
      run: xcodebuild -sdk iphonesimulator -scheme spajam-product -configuration Debug build 
